title: Zombie_fly's dev website
lang: en
description: A dev website

remote_theme: carlosperate/jekyll-theme-rtd

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock